### ISSUE TITLE
About the Quantitative results

### ISSUE THREAD

**Issue by huifu99** [YoungSeng/QPGesture#16]
You mentioned that only two speakers are used to train and test, but how do you calculate the metrics? For all baselines, they calculate the metircs along all speakers, but you only use two?

**Comment by YoungSeng** [comment]
The training and test sets computed by the proposed model and all baseline models are the same, on two speakers. See this issue: https://github.com/YoungSeng/QPGesture/issues/13

**Comment by huifu99** [comment]
Thanks for reply, but the data size becomes small when using only two speakers...

**Comment by YoungSeng** [comment]
Yes, because as far as I know there is currently no work done on all of BEAT because the amount of data is a bit large, and CaMN is also done on four English speakers. Also how to extract audio and text representations in different languages (Chinese, English, Japanese, etc.) if all speakers in BEAT are to be used may be a potential problem.

**Comment by huifu99** [comment]
OK, tks
