### ISSUE TITLE
About the fps

### ISSUE THREAD

**Issue by huifu99** [YoungSeng/QPGesture#17]
You mentioned you used 60 fps for all methods in your paper, but I found that you align all poses with 20 fps in your code 'make_beat_dataset.py'.
![image](https://github.com/YoungSeng/QPGesture/assets/115330188/87be7996-c4da-4065-80ae-a4cb49f79243)
![image](https://github.com/YoungSeng/QPGesture/assets/115330188/af4fd518-d463-46c0-b60d-4e27f2f794d9)

**Comment by YoungSeng** [comment]
Yes, our model saves data at low sampling rates but doesn't use it because all baseline models are implemented at low sampling rates, e.g. CaMN at 15fps, KNN at 15fps, End2End at 20fps...

See `make_beat_dataset.py`
https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/make_beat_dataset.py#L162

https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/make_beat_dataset.py#L182

https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/make_beat_dataset.py#L161

https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/make_beat_dataset.py#L188
